version: "2"
services: 
    ros-master:
        build: ./containers/actuation
        ports:
         - "11311:11311"
        environment:
         - ROBOT_IP=192.168.1.113
         - PYTHONUNBUFFERED=0
    ros-adapter:
        build: ./containers/adapter
        environment:
         - ROS_MASTER_URI=http://ros-master:11311/
         - PYTHONUNBUFFERED=0
        depends_on:
         - ros-master
    ros-gui:
        build: ./containers/GUI
        environment:
         - ROS_MASTER_URI=http://ros-master:11311/
         - PYTHONUNBUFFERED=0
         - DISPLAY=unix:0
        volumes:
         - /tmp/.X11-unix:/tmp/.X11-unix
        depends_on:
         - ros-master
